### ISSUE TITLE
Mysql Support

### ISSUE THREAD

**Issue by wassemgtk** [tech-sketch/skalholt#1]
Hey, are you planning to support mysql anytime soon?

**Comment by yugolf** [comment]
Thank you for submitting the issue.
I was planning to support mysql, but the priority was low.
If you need, I will give priority to it.

**Comment by wassemgtk** [comment]
It's okay don't worry. I started working on it I will finish it and share the update with you in case you're interested :)

**Comment by yugolf** [comment]
Sounds nice!
I want you to share your update to me.

**Comment by listellodavide** [comment]
I would like to contribute to skalholt to make it possible to generate mysql DDL and have full support of Mysql dbms.

**Comment by yugolf** [comment]
Thanks @listellodavide .
Skalholt is composed of 3 projects.
* [skalholt-core](https://github.com/tech-sketch/skalholt-core)
* [skalholt-ui](https://github.com/tech-sketch/skalholt-ui)
* [skalholt](https://github.com/tech-sketch/skalholt)

The logics for generating source codes are almost implemented [skalholt-core](https://github.com/tech-sketch/skalholt-core).
If you need any help, please tell me.
